language: python

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - make env
  - source env/conda/bin/activate v2x_base
  - source .github/travis/check_license.sh
  - source .github/travis/check_python_script.sh

script:
  - which tox
  - TOXENV="py${TRAVIS_PYTHON_VERSION//./}" tox

notifications:
  email: false
